var studyPresets = {
    "custom": {
        "label": "Custom",
    },
    "pharmacokinetic_single_dose": {
        "label": "Single-dose PK study test enth",
        "ester_shortcode": "ten",
        "dose": 250,
        "doseFrequency": 60,
        "durationWeeks": 4,
        "bateman": false,
        "notes": "Single administration pharmacokinetic profiling study."
    },
    "pharmacokinetic_single_dose_nandrolone": {
        "label": "Single-dose PK study nandrolone",
        "ester_shortcode": "ten",
        "dose": 150,
        "doseFrequency": 60,
        "durationWeeks": 5,
        "bateman": false,
        "notes": "Pharmacokinetic Evaluation of Three Different Intramuscular Doses of Nandrolone Decanoate",
        "source": "https://doi.org/10.1210%2Fjc.2004-1526",
    },
    "84week_nebido_trial": {
        "label": "84 Week Nebido trial",
        "ester_shortcode": "tun",
        "dose": 750,
        "doseFrequency": 70,
        "durationWeeks": 84,
        "bateman": false,
        "notes": "Pharmacokinetics and Safety of Long-Acting Testosterone Undecanoate Injections ",
        "source": "https://doi.org/10.2164/jandrol.109.009597",
    },
    "subqteste": {
        "label": "Pharmacokinetic Profile of Testosterone Enanthate",
        "ester_shortcode": "ten",
        "dose": 200,
        "doseFrequency": 7,
        "durationWeeks": 6,
        "bateman": false,
        "notes": "Pharmacokinetic Profile of Subcutaneous Testosterone Enanthate Delivered via a Novel, Prefilled Single‐Use Autoinjector: A Phase II Study",
        "source": "https://doi.org/10.1002/sm2.80",
    },
    "testewomen": {
        "label": "Pharmacokinetics of Testosterone Enanthate In Women",
        "ester_shortcode": "tenwoman",
        "dose": 250,
        "doseFrequency": 60,
        "durationWeeks": 4,
        "bateman": false,
        "notes": "Pharmacokinetics of Testosterone Enanthate After Intramuscular Injection for Transgender Men",
        "source": "https://doi.org/10.1089/andro.2020.0002",
        "study_data_set": [
            { day: 0, total_t: 75, sd: 50},
            { day: 1, total_t: 2799, sd: 1750},
            { day: 2, total_t: 2169, sd: 960},
            { day: 3, total_t: 2333, sd: 1580},
            { day: 7, total_t: 1448, sd: 470},
            { day: 14, total_t: 581, sd: 240},
            { day: 21, total_t: 272, sd: 160},
            { day: 28, total_t: 130, sd: 80},

        ],
        "molecular_weight": 288.42
    },
}